# Generated by Django 5.1.3 on 2024-11-06 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_category_quote_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='quotes.category'),
        ),
    ]
