# Generated by Django 5.1.3 on 2024-11-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0004_alter_quote_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="likes",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
